name: widgets_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-114.0.dev <4.0.0'

dependencies:
  animate_do: ^3.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
